---
title: "Excel Challenges"
author: "Anil Goyal"
date: "2024-04-10"
output: html_document
---
```{r}
library(tidyverse)
library(readxl)
library(janitor)
```

## Excel Challenge 435: Draw a boat
Using `ggplot2` here just for fun.
```{r}
map(c(0:7, 11:8),
    ~ 12 + seq(-1 * (.x ), .x, by = 1)) %>% 
  imap_dfr(~ .x %>% 
        as_tibble() %>% 
        set_names("col") %>% 
        mutate(row = .y)) %>% 
  mutate(shape = case_when(
    row %in% 1:7 ~ "A",
    row == 8 ~ "B",
    TRUE ~ "C"
  )) %>% 
  ggplot(aes(col, row)) +
  geom_point(aes(shape = shape)) +
  scale_y_reverse() +
  scale_shape_manual(values = c(3, 61, 4)) +
  theme_void() +
  theme(legend.position = "none")
```


## Excel Challenge 434: Generating Excel column names matrix
```{r}
n <- 100

{cumsum(seq(n)) - seq(n) + 1} |> 
  cellranger::num_to_letter() |>
  matrix(nrow=20)
```


## Excel Challenge 433: parsing the file/data
```{r}
df <- read_excel("Excel/Excel_Challenge_433 - Text Split.xlsx", range = cell_cols(LETTERS[1]))

df %>% 
  separate(Text, into = c("Levels", "Names"), sep = " : ") %>% 
  separate(Levels, into = paste0("Level", 1:3), sep = "\\.", fill = "right") %>% 
  separate(Names, into = c("First Name", "Last Name"), sep = " ", fill = "right")
```


## Excel Challenge 432: BIFID CIPHER

```{r}
bifid <- function(WORD){
  str_split(WORD, "")  %>% 
    unlist() %>% 
    map(~ which(matrix(LETTERS[-10], nrow = 5, byrow = TRUE) == .x, arr.ind = TRUE) %>% as.vector()) %>% 
    unlist() %>% 
    matrix(ncol = 2, byrow = TRUE) %>% 
    as.vector() %>% 
    split.default(., ((seq_along(.) - 1) %/% 2) + 1 ) %>% 
    map_chr(~matrix(LETTERS[-10], nrow = 5, byrow = TRUE)[.x[1], .x[2]]) %>% 
    str_c(collapse = "")
}

map_chr(c("BATTLE", "FLEX"), bifid)
```


## Excel Challenge 431 (Date: 10 April 2024)

```{r}
library(readxl)
library(tidyverse)

df <- read_excel("Excel/Excel_Challenge_431 - Top 3 Rankings.xlsx", range = cell_cols(LETTERS[1:8]))

df %>%
  mutate(across(-Region, ~ dense_rank(-1 * as.numeric(.x)))) %>% 
  pivot_longer(-Region, names_to = "Year", values_to = "Rank") %>% 
  filter(Rank %in% 1:3) %>% 
  summarise(rank_counts = n(),
            .by = c(Region, Rank)) %>% 
  group_by(Rank) %>% 
  slice_max(rank_counts, n = 1) %>% 
  summarise(Regions = str_c(Region, collapse = ", "))
```

## Excel Challenge 430: Flashlight

```{r}
map_dfr(1:26,
    ~ seq(from = 2*.x -1, length.out = 27 - .x) %>% 
      as_tibble() %>% 
      set_names("x") %>% 
      mutate(char = LETTERS[seq(27 - .x)],
             y = 27 - .x)) %>% 
  ggplot(aes(x, y, label = char)) +
  geom_text() +
  scale_x_reverse() +
  theme_void()
```

