---
title: "PQ Challenge"
author: "Anil Goyal"
date: "2024-04-10"
output: html_document
---
## Load libraries
```{r}
library(readxl)
library(tidyverse)
library(janitor)
```

## PQ Challenge 164
```{r}
df <- read_xlsx("PQ/PQ_Challenge_164.xlsx", range = cell_cols(LETTERS[1:5])) 
df %>% 
  pivot_longer(-Group, names_pattern = "([A-z]+)(\\d+)", names_to = c(".value", "num")) %>% 
  separate(Number, into = c("Type", "Code"), sep = 2) %>% 
  select(-num)
```


## PQ Challenge 165

## PQ Challenge 166


## PQ Challenge 167
```{r}
df <- read_xlsx("PQ/Power_Query_Challenge_167.xlsx", range = cell_cols(LETTERS[1:4]))

output <- df %>% 
  clean_names() %>% 
  group_by(dummy = cumsum(!is.na(as.integer(camp_no)))) %>% 
  group_split(.keep = FALSE) %>% 
  map_dfr(~ .x %>% 
         mutate(camp_no = camp_no[1],
                name = vaccine,
                vaccine = vaccine[1]) %>% 
        filter(row_number() != 1)) %>% 
  mutate(Notified = "Yes",
         Administered = ifelse(is.na(administration_date), "No", "Yes")) %>% 
  select(-ends_with("date")) %>% 
  complete(camp_no, name, fill = list(Notified = "No")) %>% 
  fill(vaccine, .direction = "down") %>% 
  mutate(camp_no = as.double(row_number()),
         .by = vaccine) %>% 
  relocate(vaccine, .after = camp_no) %>% 
  rename(`Camp No` = camp_no, Name = name, Vaccine = vaccine)

output

result <- read_xlsx("PQ/Power_Query_Challenge_167.xlsx", 
                    range = cell_cols(LETTERS[7:11]), 
                    na = "NA") 
identical(result, output)
```


## PQ Challenge 168
```{r}
df <- read_xlsx("PQ/Power_Query_Challenge_168.xlsx", range = cell_cols(LETTERS[1:2]))

df %>% 
  mutate(Item = accumulate(sort(Item), ~ paste(.x, .y, sep = "/") ),
         .by = Store)
```


## PQ Challenge 169: Extract specific strings
It combines both lookahead and lookbehind in one string
```{r}
df <- read_xlsx("PQ/PQ_Challenge_169.xlsx", range = cell_cols(LETTERS[1]))
df %>% 
  mutate(Codes = map_chr(String, ~ str_extract_all(.x, pattern = "(?<=\\b)[A-Z]+\\d+[A-Z0-9]+(?=\\b)") %>% 
                           unlist() %>% 
                           str_c(collapse = ", ")))
```


## PQ Challenge 170: Weekdays and Weekends
```{r}
df <- read_xlsx("PQ/PQ_Challenge_170.xlsx", range = cell_cols(LETTERS[1:3]))

df %>% 
  group_by(`Day Type` = c("Weekday", "Weekend")[1 + weekdays(Date, abbreviate = TRUE) %in% c("Sat", "Sun")], Item) %>% 
  summarise(Sales = sum(Sale), .groups = 'drop') %>% 
  summarise(`Total Sales` = sum(Sales), 
            `Highest Selling Item` = str_c(Item[Sales == max(Sales)], collapse = ", "),
            `Lowest Selling Item` = str_c(Item[Sales == min(Sales)], collapse = ", "),
            .by = `Day Type`)
```


## PQ Challenge 171

```{r}
df <- read_xlsx("PQ/PQ_Challenge_171.xlsx", range = cell_cols(LETTERS[1:6]))

split.default(1:6, (0:5 %% 3) + 1) %>% 
  map_dfr(~df %>% 
        select(all_of(.x)) %>% 
        rename_with(~ paste0("Col", 1:2))) %>% 
  filter(if_any(everything(), ~!is.na(.)))
```


## PQ Challenge 172

```{r}
library(readxl)
library(tidyverse)

df <- read_xlsx("PQ/PQ_Challenge_172.xlsx", range = cell_cols(LETTERS[1:6]))
df %>% 
  janitor::clean_names() %>% 
  separate(share_percent, into = paste0("Share", 1:2), convert = TRUE) %>% 
  pivot_longer(cols = c(starts_with("agent"), starts_with("Share")), 
               names_pattern = "(\\D*)(\\d)",
               names_to = c(".value", "num"),
               values_drop_na = TRUE) %>% 
  complete(fill = list(Share = 100)) %>% 
  mutate(amt = amount * commission_percent * Share/10000) %>% 
  summarise(Commission = sum(amt), .by = agent) %>% 
  janitor::adorn_totals()
```

## PQ Challenge 173
```{r}
df <- read_xlsx("PQ/PQ_Challenge_173.xlsx", range = cell_cols(LETTERS[1:2]))

df %>% 
  group_by(
    Year = year(Date),
    Quarter = as.factor(quarter(Date)),
    Month = month(Date, abbr = TRUE, label = TRUE)
  ) %>% 
  summarise(
    `Total Sale` = sum(Sale),
    .groups = 'drop'
  ) %>% 
  mutate(
    `Sale %` = scales::percent(`Total Sale`/sum(`Total Sale`),
                               accuracy = 1),
    .by = Year
  ) %>% 
  group_split(Year) %>% 
  map_dfr(janitor::adorn_totals) %>% 
  mutate(`Sale %` = ifelse(`Sale %` == "-", "100%", `Sale %`))
```

## PQ Challenge 174
```{r}
df <- read_xlsx("PQ/PQ_Challenge_174.xlsx", range = cell_cols(LETTERS[1:4]))
df %>% 
  clean_names() %>% 
  pivot_longer(contains("date"), values_to = "dates", names_to = NULL) %>% 
  mutate(dates = as.Date(dates)) %>% 
  group_by(emp) %>% 
  mutate(from_date = floor_date(dates, "month")) %>% 
  complete(from_date = seq.Date(min(from_date), max(from_date), "month")) %>% 
  fill(sales) %>% 
  mutate(from_date = case_when(row_number() == 1 ~ dates,
                               TRUE ~ from_date),
         to_date = case_when(row_number() == n() ~ dates,
                             TRUE ~ ceiling_date(from_date, "month") - days(1))) %>% 
  select(-dates) %>% 
  mutate(month_sales = sales * as.numeric(to_date - from_date + 1)/as.numeric(sum(to_date - from_date + 1))) %>% 
  ungroup() %>% 
  group_by(emp, Year = year(from_date)) %>% 
  mutate(running_sales = cumsum(month_sales)) %>% 
  ungroup() %>% 
  select(Emp = emp, `From Date` = from_date, `To Date` = to_date, `Monthly Sales` = month_sales, `Running Total` = running_sales)
```

## PQ Challenge 175
```{r}

df <- read_xlsx("PQ/PQ_Challenge_175.xlsx", range = cell_cols(LETTERS[1:3])) %>% 
  clean_names()

df %>% 
  inner_join(
    df,
    by = join_by(family == family, closest(generation_no < generation_no)),
    suffix = c("", "_next")
  ) %>% 
  rename(next_generation = name_next) %>% 
  unite("relationship", starts_with("generation_no"), remove = TRUE, sep = " - ") %>% 
  relocate(relationship, .after = next_generation) %>% 
  arrange(family, relationship, name, next_generation)

```

## PQ Challenge 176
```{r}
df <- read_xlsx("PQ/PQ_Challenge_176.xlsx", range = cell_cols(LETTERS[1:3]))

df %>% 
  separate_wider_delim(cols = starts_with("Column"), delim = ", ", names_sep = "_", too_few = "align_start") %>% 
  pivot_longer(cols = -Group, names_sep = "_", names_to = c(".value", "Name"), values_transform = list(Column2 = as.integer)) %>% 
  select(-Name) %>% 
  filter(!is.na(Column1) | !is.na(Column1)) %>% 
  mutate(Column2 = cumsum(coalesce(Column2, 0)),
         .by = Group)
```

## PQ Challenge 178
```{r}
df <- read_xlsx("PQ/PQ_Challenge_178.xlsx", range = cell_cols(LETTERS[1:5])) %>% 
  clean_names(case = "title")

df |> 
  pivot_longer(-Emp, names_to = c(".value", "Change"), names_sep = " ") |> 
  na.omit()
```


## PQ Challenge 180
```{r}
df <- read_xlsx("PQ/PQ_Challenge_180.xlsx", range = cell_cols(LETTERS[1:2])) %>% 
  clean_names()

## Approach-1
df %>% 
  mutate(emp = case_match(sales, NA ~ emp_month)) %>% 
  fill(emp, .direction = "down") %>% 
  na.omit() %>% 
  summarise(
    total_sales = sum(sales),
    max_sales_change = max(abs(diff(c(NA, sales))), na.rm = TRUE),
    from_to_month = paste(lag(emp_month), 
                          emp_month, 
                          sep = " - ")[coalesce(abs(diff(c(NA, sales))) == 
                                                  max(abs(diff(c(NA, sales))), na.rm = TRUE), FALSE)],
    .by = emp
  )


## Approach-2
df %>% 
  mutate(emp = case_match(sales, NA ~ emp_month)) %>% 
  fill(emp, .direction = "down") %>% 
  na.omit() %>% 
  reframe(
    total_sales = sum(sales),
    sales_change = abs(diff(c(NA, sales))),
    from_to_month = paste(lag(emp_month), 
                          emp_month, 
                          sep = " - "),
    .by = emp
  ) %>% 
  summarise(
    total_sales = max(total_sales),
    max_sales_change = max(sales_change, na.rm = TRUE),
    from_to_month = from_to_month[which.max(sales_change)],
    .by = emp
  )
```

